{"uuid": "b56acd98-38c4-4477-8ccc-510c3462e049", "children": ["a642231a-3679-4752-a16c-66fb8bc6982f"], "befores": [{"name": "testcase_data", "status": "broken", "statusDetails": {"message": "AttributeError: function not available in class-scoped context\n", "trace": "  File \"/Users/elio/Library/Python/3.9/lib/python/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/elio/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/elio/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/elio/code/python/jenkins-pytest-demo/testcases/user_service_test/test_userservice.py\", line 9, in testcase_data\n    testcase_name = request.function.__name__\n  File \"/Users/elio/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 82, in provide\n    raise AttributeError(\n"}, "start": 1689583131609, "stop": 1689583131609}], "start": 1689583131609, "stop": 1689583131714}